DESIGN_NAME: ecc_design
VERILOG_FILES: 
- dir::rtl/typedefs.sv
- dir::rtl/ecc_design.sv
- dir::rtl/MRSC_encoder.sv
- dir::rtl/MRSC_decoder.sv
- dir::rtl/TBEC_RSC_encoder.sv
- dir::rtl/TBEC_RSC_decoder.sv

CLOCK_PORT: null
USE_SLANG: true

PL_TARGET_DENSITY_PCT: 75
FP_ASPECT_RATIO: 1
IO_PIN_ORDER_CFG: dir::pin_order.cfg
